### PR TITLE
first parse test passes

### PR DESCRIPTION
**Pull request by WardCunningham**
This is a start on the parser described in issue #1.

I had intended to make this more complete but have instead learned more about cross-fork pull requests in github. Sorry to have run out of time this morning.

### CODE REVIEW

**Comment by WardCunningham** [comment]
This now handles the two test cases @bracken and I selected. My intention is that a parser would work line by line and see if it finds any/many markers.

**Comment by WardCunningham** [comment]
I couldn't get `grunt watch` to run the tests. Use `grunt build` instead.

**Comment by WardCunningham** [comment]
Multiple markers in multiple coordinate formats.

image


Standard editor works the standard way. Links allowed in caption and marker popup text. This one includes a google street view link.

image

Try this online:
[http://localhost:3000/testing-map-enhancements.html](http://localhost:3000/testing-map-enhancements.html)

**Comment by WardCunningham** [comment]
The map plugin now exposes to other items that it holds markers defined by its markup. The map item announces the availability of the marker api by attaching class "marker-source" at the div .item level in the dom. A plugin making this declaration must provide two api entry point though either can answer null if they can't meet the api expectation.

Here we demonstrate the two possible calls.

* getData() returns markers in the same format held in the map plugin.
* getGeo() returns markers as a geojson FeatureCollection representing the same information.

We now demonstrate using these api from the inspector console for the Testing Map Enhansements page.

Expose markers as native data.
image

Expose markers as geojson.
image

**Comment by WardCunningham** [comment]
I've added code to consume markers sourced by other items, now only other maps.

```
    # find and add markers from candidate items
    candidates = $(".item:lt(#{$('.item').index($item)})")
    if (who = candidates.filter ".marker-source").size()
        showMarkers div.markerData() for div in who
```

I've revised about page adds this description.

image

**Comment by WardCunningham** [comment]
I suggest shift-double-click add a marker to the markup.

I also suggest that map be configured to surround the markers present in the markup but not markers imported from other marker-sources. 

Absent markers in the markup, the map could be positioned by looking for legacy annotations in the item, other geo information in the item, imported markers, or a default location like New York City.

Newly created maps would appear for the default location, scrolled to the desired location, and shift-double-clicked to place some markers.

**Comment by WardCunningham** [comment]
@paul90 may have some opinions since I have undone some of his work.

**Comment by paul90** [comment]
Some opinions?

Not sure what work of mine you have undone, the only work I did on this plugin was switch to using leaflet. The important thing is that much needed functionality is being added.

I assume that the plan is to do the development here, in @clemsos's fork rather than say in a branch of the main repo. Though that shouldn't prevent releasing this work as `wiki-plugin-map@next` as you reach stable points that you want to make more widely available.

Think I would suggest creating an issue over in fedwiki/wiki-plugin-map linking to this repo, with a list of the features being added, so any other with an interested in maps can't miss it.

I look forward to seeing pull request from here, back into the main repo, as the work here progresses.

**Comment by clemsos** [comment]
Hi all, 
the map-plugin already made great progresses. Sorry I was not part of it. About this rep, I forked it because I could not write on the fedwiki/wiki-map-plugin rep but of course the goal is to merge everything that has been done into the main rep in the wiki organization.

I am merging this PR now, as most of it is already working. We can open new ones for the different tasks that still to be done for the map plugin.

**Pull request merged**
